steps:
  mtaBuild:
    platform: 'CF'
  cloudFoundryDeploy:
    cloudFoundry:
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com' 
      org: '6a0dbc6ctrial'
      space: 'dev'
      credentialsId: 'CF-jenkins-credentials-id'